name: Mark server docker image as latest

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE_NAME: colanode/server

jobs:
  tag-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Pull version image
        run: docker pull ${{ env.REGISTRY }}/${{ env.SERVER_IMAGE_NAME }}:${{ env.VERSION }}

      - name: Tag and push as latest
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.SERVER_IMAGE_NAME }}:${{ env.VERSION }} ${{ env.REGISTRY }}/${{ env.SERVER_IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.SERVER_IMAGE_NAME }}:latest
